name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      # Modified step to handle package-lock.json issues
      - name: Create package-lock.json if needed
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "package-lock.json not found. This could cause dependency issues..."
            echo "📦 Creating package-lock.json from scratch..."
            npm install --package-lock-only
            echo "✅ Generated new package-lock.json file"
          else
            echo "✅ package-lock.json exists"
          fi
      
      # Fix npm install to be more reliable
      - name: Install dependencies
        run: |
          # First try to install normally
          echo "📦 Installing dependencies..."
          if npm install; then
            echo "✅ Dependencies installed successfully"
          else
            echo "⚠️ Standard install failed, trying with legacy-peer-deps..."
            npm install --legacy-peer-deps
          fi
      
      # Build the application
      - name: Build Next.js app
        run: npm run build
      
      # Deploy to Cloudflare Pages directly
      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "🚀 Deploying to Cloudflare Pages..."
          npx wrangler pages deploy out \
            --project-name=cryptofuse \
            --branch="${{ github.head_ref || github.ref_name }}"
